const statusIcons = {
  sent: '<i class="fas fa-check-circle" style="color: green; font-size: 40px;"></i>',
  pending: '<i class="fas fa-hourglass-half" style="color: orange; font-size: 40px;"></i>',
  failed: '<i class="fas fa-times-circle" style="color: red; font-size: 40px;"></i>'
};

function generateReceipt() {
  const senderName = document.getElementById('senderName').value.trim();
  const senderAcc  = document.getElementById('senderAcc').value.trim();
  const receiverName = document.getElementById('receiverName').value.trim();
  const receiverAcc  = document.getElementById('receiverAcc').value.trim();
  const bankName = document.getElementById('bankName').value.trim();
  const amount   = document.getElementById('amount').value.trim();
  const memo     = document.getElementById('memo').value.trim();
  const status   = document.getElementById('status').value;

  const statusIcon = statusIcons[status] || "";

  const receiptHtml = `
    <div class="receipt-box">
      <div class="status-icon">${statusIcon}</div>
      <h3>Bank Transfer Receipt</h3>
      <div class="receipt-item"><strong>Status:</strong> ${status.toUpperCase()}</div>
      <div class="receipt-item"><strong>Bank:</strong> ${bankName}</div>
      <div class="receipt-item"><strong>Sender:</strong> ${senderName} (${senderAcc})</div>
      <div class="receipt-item"><strong>Receiver:</strong> ${receiverName} (${receiverAcc})</div>
      <div class="receipt-item"><strong>Amount:</strong> $${parseFloat(amount).toFixed(2)}</div>
      <div class="receipt-item"><strong>Memo:</strong> ${memo}</div>
      <div style="margin-top:15px; font-size:12px; color:gray;">Generated by Bank Transfer Generator</div>
    </div>
  `;

  document.getElementById('form-page').style.display = 'none';
  document.getElementById('receipt-page').style.display = 'block';
  document.getElementById('receipt-content').innerHTML = receiptHtml;
}

function goBack() {
  document.getElementById('form-page').style.display = 'block';
  document.getElementById('receipt-page').style.display = 'none';
}

function downloadReceipt() {
  const element = document.getElementById('receipt-content');
  html2pdf().from(element).save('Bank-Transfer-Receipt.pdf');
}