
const bankLogos = {
  "Chase Bank": "https://1000logos.net/wp-content/uploads/2017/06/Chase-logo.png",
  "Bank of America": "https://1000logos.net/wp-content/uploads/2017/06/Bank-of-America-logo.png",
  "Wells Fargo": "https://1000logos.net/wp-content/uploads/2017/06/Wells-Fargo-logo.png",
  "Citi Bank": "https://1000logos.net/wp-content/uploads/2017/06/Citibank-logo.png",
  "HSBC": "https://1000logos.net/wp-content/uploads/2017/06/HSBC-logo.png"
};

const statusIcons = {
  sent: '<i class="fas fa-check-circle" style="color: green; font-size: 24px;"></i>',
  pending: '<i class="fas fa-hourglass-half" style="color: orange; font-size: 24px;"></i>',
  failed: '<i class="fas fa-times-circle" style="color: red; font-size: 24px;"></i>'
};

function generateReceipt() {
  const senderName = document.getElementById('senderName').value.trim();
  const senderAcc = document.getElementById('senderAcc').value.trim();
  const receiverName = document.getElementById('receiverName').value.trim();
  const receiverAcc = document.getElementById('receiverAcc').value.trim();
  const bankName = document.getElementById('bankName').value.trim();
  const amount = document.getElementById('amount').value.trim();
  const memo = document.getElementById('memo').value.trim();
  const status = document.getElementById('status').value;

  const bankLogo = bankLogos[bankName] || "";
  const statusIcon = statusIcons[status] || "";

  const today = new Date();
  const date = today.toLocaleDateString();
  const time = today.toLocaleTimeString();
  const dateTime = `${date} ${time}`;

  const receiptHtml = \`
    <div class="receipt-box">
      \${bankLogo ? \`<div class="bank-logo"><img src="\${bankLogo}" alt="\${bankName} Logo"></div>\` : ''}
      <h3>Bank Transfer Receipt</h3>
      <div class="receipt-detail"><strong>Status:</strong> \${status.toUpperCase()} \${statusIcon}</div>
      <div class="receipt-detail"><strong>Date & Time:</strong> \${dateTime}</div>
      <div class="receipt-detail"><strong>Bank:</strong> \${bankName}</div>
      <hr>
      <div class="receipt-detail"><strong>Sender Name:</strong> \${senderName}</div>
      <div class="receipt-detail"><strong>Sender Account:</strong> \${senderAcc}</div>
      <div class="receipt-detail"><strong>Receiver Name:</strong> \${receiverName}</div>
      <div class="receipt-detail"><strong>Receiver Account:</strong> \${receiverAcc}</div>
      <div class="receipt-detail"><strong>Amount:</strong> $\${parseFloat(amount).toFixed(2)}</div>
      <div class="receipt-detail"><strong>Memo:</strong> \${memo}</div>
      <div class="footer-note">Generated by Bank Transfer Generator</div>
    </div>
  \`;

  document.getElementById('form-page').style.display = 'none';
  document.getElementById('receipt-page').style.display = 'block';
  document.getElementById('receipt-content').innerHTML = receiptHtml;
}

function goBack() {
  document.getElementById('form-page').style.display = 'block';
  document.getElementById('receipt-page').style.display = 'none';
}

function downloadReceipt() {
  const element = document.getElementById('receipt-content');
  html2pdf().from(element).save('Bank-Transfer-Receipt.pdf');
}
